#Headleass Service
---
apiVersion: v1
kind: Service
metadata:
  name: es-client
  namespace: elasticsearch
  labels:
    role: client
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
    role: client
  clusterIP: None
  ports:
  - port: 9300
    targetPort: 9300

---
#es-client Statefulset
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: es-client
  namespace: elasticsearch
  labels:
    app: elasticsearch
    role: client
spec:
  selector:
    matchLabels:
      app: elasticsearch
      role: client
  serviceName: es-client
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      name: es-client
      labels: 
        app: elasticsearch
        role: client
    spec:
      terminationGracePeriodSeconds: 0
      initContainers: #init containers for disable swap and change max map count and increase
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: init-sysctl #change sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers: #define elasticsearch container 
      - name: es-client
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        ports:
        - containerPort: 9300
          name: es-tunnel
        - containerPort: 9200
          name: es-http
        volumeMounts:
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: es-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch-client.yml
                path: elasticsearch.yml

