apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: elasticsearch
  labels:
    app: kibana
    role: kibana
data:
  kibana.yml: |
    server.port: "5601"
    server.name: "kibana"
    server.host: "0.0.0.0"
    elasticsearch.url: http://es-client:9200
    xpack.security.sessionTimeout: 600000 #session timeout
    xpack.license.self_generated.type: base #security liceance base
    xpack.security.authProviders: [basic]
    xpack.security.enabled: true
    xpack.monitoring.enabled: true
    server.ssl.enabled: false
