apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  labels:
    app: kibana
    role: kibana
data:
  kibana.yml: |
    server:
      name: "kibana"
      port: 5601
    elasticsearch.url: "http://es-master:9200"