apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: elasticsearch
  labels:
    app: kibana
    role: kibana
data:
  kibana.yml: |
    server.port: 5601
    server.name: ${HOSTNAME}.kibana
    server.host: 0.0.0.0
    elasticsearch.hosts: 
    - "http://es-client:9200"
    # xpack.security.enabled: true
    xpack.monitoring.enabled: true
    # xpack.security.sessionTimeout: 600000 #session timeout
    server.ssl.enabled: false