apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: elasticsearch
  labels:
    app: kibana
    role: kibana
data:
  kibana.yml: |
    server.port: "kibana:5601"
    server.name: "kibana"
    elasticsearch.url: "http://es-client:9200"
