#Headleass Service
---
apiVersion: v1
kind: Service
metadata:
  name: es-data
  namespace: elasticsearch
spec:
  selector:
    app: es-data
  clusterIP: None
  ports:
  - port: 9300
    targetPort: 9300

---
#es-data Statefulset
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: es-data
  namespace: elasticsearch
spec:
  selector:
    matchLabels:
      app: es-data
  serviceName: es-data
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels: 
        app: es-data
    spec:
      terminationGracePeriodSeconds: 0
      initContainers: #init containers for disable swap and change max map count and increase
      - name: init-sysctl #change sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers: #define elasticsearch container 
      - name: es-data
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        ports:
        - containerPort: 9300
          name: es-tunnel
        - containerPort: 9200
          name: es-http
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: es-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
  volumeClaimTemplates:
    - metadata:
        name: es-data
        namespace: elasticsearch
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

