apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: elasticsearch
data:
  elasticsearch-data.yml: |
    cluster.name: es-oryan
    node.name: ${HOSTNAME}.es-data
    network.host: 0.0.0.0
    network.publish_host: ${HOSTNAME}.es-data
    bootstrap.memory_lock: false
    discovery.zen.minimum_master_nodes: 2
    discovery.zen.ping.unicast.hosts: 
      - "es-master-1.es-master"
      - "es-master-2.es-master"
      - "es-master-0.es-master"
      - "es-data-1.es-data"
      - "es-data-2.es-data"
      - "es-data-0.es-data"
      - "es-client-1.es-client"
      - "es-client-2.es-client"
      - "es-client-0.es-client"
    # xpack.security.enabled: true
    xpack.monitoring.enabled: true
    # xpack.security.transport.ssl.client_authentication: optional
    http.port: "9200"
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    node.data:  "true"
    node.ingest: "false"
    node.master: "false"
    # xpack.license.self_generated.type: basic
    # xpack.monitoring.elasticsearch.collection.enabled: true
  elasticsearch-master.yml: |
    cluster.name: es-oryan
    node.name: ${HOSTNAME}.es-master
    network.host: 0.0.0.0
    network.publish_host: ${HOSTNAME}.es-master
    transport.tcp.port: 9300
    discovery.zen.ping.unicast.hosts: 
      - "es-master-1.es-master"
      - "es-master-2.es-master"
      - "es-master-0.es-master"
      - "es-data-1.es-data"
      - "es-data-2.es-data"
      - "es-data-0.es-data"
      - "es-client-1.es-client"
      - "es-client-2.es-client"
      - "es-client-0.es-client"
    cluster.initial_master_nodes:
      - "es-master-1.es-master"
      - "es-master-2.es-master"
      - "es-master-0.es-master"
    # xpack.security.enabled: true
    xpack.monitoring.enabled: true
    # xpack.license.self_generated.type: basic
    # xpack.monitoring.elasticsearch.collection.enabled: true
    http.port: 9200
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    discovery.zen.minimum_master_nodes: 2
    # xpack.security.transport.ssl.client_authentication: optional
    node.data:  false
    node.ingest: false
    node.master: true
  elasticsearch-client.yml: |
    cluster.name: es-oryan
    node.name: ${HOSTNAME}.es-client
    network.host: 0.0.0.0
    network.publish_host: ${HOSTNAME}.es-client
    bootstrap.memory_lock: false
    discovery.zen.minimum_master_nodes: 2
    discovery.zen.ping.unicast.hosts: 
      - "es-master-1.es-master"
      - "es-master-2.es-master"
      - "es-master-0.es-master"
      - "es-data-1.es-data"
      - "es-data-2.es-data"
      - "es-data-0.es-data"
      - "es-client-1.es-client"
      - "es-client-2.es-client"
      - "es-client-0.es-client"
    # xpack.security.enabled: true
    xpack.monitoring.enabled: true
    # xpack.license.self_generated.type: basic
    # xpack.security.transport.ssl.client_authentication: optional
    # xpack.monitoring.elasticsearch.collection.enabled: true
    http.port: "9200"
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    node.data:  "false"
    node.ingest: "true"
    node.master: "false"
  ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
  ELASTIC_USERNAME: "elastic"
  ELASTIC_PASSWORD: "password"


    
    
